### ISSUE TITLE
Use swiftlint on CI

### ISSUE THREAD

**Issue by badboy** [mozilla/glean_parser#102]
With #101 we have swift code which we can lint using `swiftlint`.
We should see if we can get that on Linux and then also run it during CI.

**Comment by badboy** [comment]
It's ... okayish, but not easy (no binary releases). See also https://github.com/realm/SwiftLint/issues/732

**Comment by chutten** [comment]
Moved to: https://bugzilla.mozilla.org/show_bug.cgi?id=1703819
