### ISSUE TITLE
[Components] glean must update the `glean_parser` packages if new versions are required

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/glean_parser#12]
* Glean Parser version: 0.6.0
* Python version: 3.7.0
* Operating System: Mac OS (building android-components)

### Description

Try to build Android Components from scratch.

### What I Did

The sample-glean component fails to build with the crash log below:
<details>
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':samples-glean:generateMetricsSourceForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.GradleException: Process '[/Users/jalmeida/src/android-components/samples/glean/build/bootstrap/Miniconda3/bin/python, -m, glean_parser, translate, -f, kotlin, -o, /Users/jalmeida/src/android-components/samples/glean/build/telemetry/src/debug/kotlin, /Users/jalmeida/src/android-components/samples/glean/metrics.yaml]' finished with non-zero exit value 1:

/Users/jalmeida/src/android-components/samples/glean/metrics.yaml: Additional properties are not allowed ('lifetime' was unexpected)

Failed validating 'additionalProperties' in schema['additionalProperties']['additionalProperties']:
    {'additionalProperties': False,
     'properties': {'application_property': {'default': False,
                                             'description': 'If true, the '
                                                            'metric '
                                                            'contains a '
                                                            'property that '
                                                            'is related to '
                                                            'the\n'
                                                            'application, '
                                                            'and is reset '
                                                            'only at '
                                                            'application '
                                                            'restarts. '
                                                            'Only one of\n'
                                                            '`user_property` '
                                                            'or '
                                                            '`application_property` '
                                                            'may be '
                                                            '`true`.\n',
                                             'title': 'Application '
                                                      'property',
                                             'type': 'boolean'},
                    'bugs': {'description': 'A list of bugs (e.g. Bugzilla '
                                            'and Github) that are relevant '
                                            'to this\n'
                                            'metric, e.g., tracking its '
                                            'original implementation or '
                                            'later changes to\n'
                                            'it. If a number, it is an ID '
                                            'to an issue in the default '
                                            'tracker (e.g.\n'
                                            "Mozilla's Bugzilla instance). "
                                            'If a string, it must be a URI '
                                            'to a bug\n'
                                            'page in a tracker.\n',
                             'items': {'anyOf': [{'type': 'integer'},
                                                 {'format': 'uri',
                                                  'type': 'string'}]},
                             'minItems': 1,
                             'title': 'Related bugs',
                             'type': 'array'},
                    'denominator': {'allOf': [{'$ref': '#/definitions/snake_case'}],
                                    'description': 'The name of the '
                                                   'denominator value for '
                                                   'a use counter.\n'
                                                   '\n'
                                                   'Valid when `type` is '
                                                   '`use_counter`.\n',
                                    'title': 'Denominator'},
                    'description': {'description': 'A textual description '
                                                   'of what this metric '
                                                   'does, means, its edge '
                                                   'cases\n'
                                                   'and any other helpful '
                                                   'information.\n',
                                    'title': 'Description',
                                    'type': 'string'},
                    'disabled': {'default': False,
                                 'description': 'If true, the metric is '
                                                'disabled, and any metric '
                                                'collection on it will\n'
                                                'be silently ignored at '
                                                'runtime.\n',
                                 'title': 'Disabled',
                                 'type': 'boolean'},
                    'expires_after_build_date': {'anyOf': [{'format': 'date-time',
                                                            'type': 'string'},
                                                           {'type': 'null'}],
                                                 'default': None,
                                                 'description': 'If '
                                                                'provided, '
                                                                'an ISO '
                                                                '8601 date '
                                                                'that '
                                                                'represents '
                                                                'the day '
                                                                'from '
                                                                'which '
                                                                'any\n'
                                                                'collection '
                                                                'using the '
                                                                'metric '
                                                                'should be '
                                                                'silently '
                                                                'ignored. '
                                                                'The date '
                                                                'is\n'
                                                                'checked '
                                                                'at build '
                                                                'time. If '
                                                                'the '
                                                                'specified '
                                                                'date is '
                                                                'passed, '
                                                                'this '
                                                                'metric '
                                                                'is\n'
                                                                'seen as '
                                                                'expired.\n',
                                                 'title': 'Expires after '
                                                          'build date.'},
                    'extra_keys': {'additionalProperties': {'maxLength': 80,
                                                            'type': 'string'},
                                   'default': {},
                                   'description': 'The acceptable keys on '
                                                  'the "extra" object sent '
                                                  'with events. This is '
                                                  'an\n'
                                                  'object mapping the key '
                                                  'to a description.\n'
                                                  '\n'
                                                  'Valid when `type` is '
                                                  '`event`.\n',
                                   'maxProperties': 10,
                                   'propertyNames': {'$ref': '#/definitions/very_short_id'},
                                   'title': 'Extra keys',
                                   'type': 'object'},
                    'labeled': {'description': 'Record multiple separate '
                                               'metrics under different '
                                               'labels.\n'
                                               'The labels may be known '
                                               'ahead of time (provided in '
                                               'the `labels`\n'
                                               'property) or be dynamic at '
                                               'runtime.\n',
                                'title': 'Labeled metric',
                                'type': 'boolean'},
                    'labels': {'description': 'A list of labels for a '
                                              'labeled metric or use '
                                              'counter.\n'
                                              '\n'
                                              'Valid when `labeled` is '
                                              '`true`.\n',
                               'items': {'$ref': '#/definitions/snake_case'},
                               'title': 'Labels',
                               'type': 'array'},
                    'notification_emails': {'description': 'A list of '
                                                           'email '
                                                           'addresses to '
                                                           'notify for '
                                                           'important '
                                                           'events with '
                                                           'the\n'
                                                           'metric or when '
                                                           'people with '
                                                           'context or '
                                                           'ownership for '
                                                           'the metric '
                                                           'need to\n'
                                                           'contacted.\n',
                                            'items': {'format': 'email',
                                                      'type': 'string'},
                                            'minItems': 1,
                                            'title': 'Notification emails',
                                            'type': 'array'},
                    'objects': {'description': 'The valid event objects. '
                                               'This is a list of '
                                               'strings.\n'
                                               '\n'
                                               'Valid when `type` is '
                                               '`event`.\n',
                                'items': {'$ref': '#/definitions/very_short_id'},
                                'minItems': 1,
                                'title': 'Objects',
                                'type': 'array'},
                    'reviews': {'description': 'A list of URLs to any data '
                                               'collection reviews '
                                               'relevant to the metric.\n',
                                'items': {'format': 'uri',
                                          'type': 'string'},
                                'title': 'Review references',
                                'type': 'array'},
                    'send_in_pings': {'default': ['default'],
                                      'description': 'Which pings the '
                                                     'metric should be '
                                                     'sent on. If not '
                                                     'specified, the '
                                                     'metric\n'
                                                     'is sent on the '
                                                     '"default ping", '
                                                     'which is the '
                                                     '"events" ping for '
                                                     'events,\n'
                                                     'and the "metrics" '
                                                     'ping for everything '
                                                     'else. Most metrics '
                                                     "don't need to\n"
                                                     'specify this.\n',
                                      'items': {'$ref': '#/definitions/snake_case'},
                                      'title': 'Send in pings',
                                      'type': 'array'},
                    'time_unit': {'description': 'Specifies the unit that '
                                                 'the metric will be '
                                                 'stored and displayed in. '
                                                 'If\n'
                                                 'not provided, it '
                                                 'defaults to '
                                                 'milliseconds. Time '
                                                 'values are sent to the\n'
                                                 'backend as integers, so '
                                                 '`time_unit` also implies '
                                                 'the maximum\n'
                                                 'resolution at which '
                                                 'timespans are recorded. '
                                                 'Valid when `type` is\n'
                                                 '`timespan`, '
                                                 '`timing_distribution` or '
                                                 '`datetime`.\n',
                                  'enum': ['nanosecond',
                                           'microsecond',
                                           'millisecond',
                                           'second',
                                           'minute',
                                           'hour',
                                           'day'],
                                  'title': 'Time unit'},
                    'type': {'description': 'Specifies the type of a '
                                            'metric, like "counter" or '
                                            '"event". This defines\n'
                                            'which operations are valid '
                                            'for the metric, how it is '
                                            'stored and how\n'
                                            'data analysis tooling '
                                            'displays it.\n'
                                            '\n'
                                            'The supported types are:\n'
                                            '  - boolean: true or false.\n'
                                            '  - string: a Unicode string '
                                            'value.\n'
                                            '  - string_list: a list of '
                                            'Unicode strings.\n'
                                            '  - enumeration: a string '
                                            'with a fixes set of values. '
                                            'Additional properties:\n'
                                            '    `values`.\n'
                                            '  - counter: A numeric value '
                                            'that can only be '
                                            'incremented.\n'
                                            '  - timespan: Represents a '
                                            'time interval. Additional '
                                            'properties: `time_unit`.\n'
                                            '  - timing_distribution: '
                                            'Record the distribution of '
                                            'multiple timings.\n'
                                            '    Additional properties: '
                                            '`time_unit`.\n'
                                            '  - datetime: A date/time '
                                            'value.  Represented as an ISO '
                                            'datetime in UTC.\n'
                                            '    Additional properties: '
                                            '`time_unit`.\n'
                                            '  - use_counter: Records the '
                                            'value of one of more values '
                                            'in relation\n'
                                            '    to another value. '
                                            'Represented internally as a '
                                            'list of numerators\n'
                                            '    and denominator, all of '
                                            'which can be incremented '
                                            'separately.\n'
                                            '    Additional properties: '
                                            '`labels`, `denominator`.\n'
                                            '  - usage: Record whether a '
                                            'feature is used. This is '
                                            'functionally\n'
                                            '    equivalent to a boolean '
                                            'metric type, except the '
                                            'analysis and\n'
                                            '    visualization side may '
                                            'present it differently, '
                                            'knowing that it\n'
                                            '    indicates the usage of a '
                                            'feature.\n'
                                            '  - rate: Record the rate of '
                                            'an event over time. This is '
                                            'functionally\n'
                                            '    equivalent to a counter, '
                                            'except the analysis and '
                                            'visualization\n'
                                            '    will tie it to the '
                                            'duration of the ping to '
                                            'display it as a rate\n'
                                            '    over time.\n'
                                            '  - event: Record a specific '
                                            'event (with optional '
                                            'metadata).\n'
                                            '    Additional properties: '
                                            '`objects` and `extra_keys`.\n'
                                            '  - uuid: Record a UUID v4.\n',
                             'enum': ['boolean',
                                      'string',
                                      'string_list',
                                      'enumeration',
                                      'counter',
                                      'timespan',
                                      'timing_distribution',
                                      'datetime',
                                      'use_counter',
                                      'usage',
                                      'rate',
                                      'event',
                                      'uuid'],
                             'title': 'Metric type',
                             'type': 'string'},
                    'user_property': {'default': False,
                                      'description': 'If true, the metric '
                                                     'contains a property '
                                                     'that is part of the '
                                                     "user's\n"
                                                     'profile and is never '
                                                     'reset. Only one of '
                                                     '`user_property` or\n'
                                                     '`application_property` '
                                                     'may be `true`.\n',
                                      'title': 'User property',
                                      'type': 'boolean'},
                    'values': {'description': 'A list of strings that are '
                                              'supported enum values.\n'
                                              '\n'
                                              'Valid when `type` is '
                                              '`enum`.\n',
                               'items': {'type': 'string'},
                               'title': 'Supported values',
                               'type': 'array'},
                    'version': {'description': 'The version of the metric. '
                                               'A monotonically increasing '
                                               'value. If not\n'
                                               'provided, defaults to 0.\n',
                                'title': 'Metric version'}},
     'required': ['type', 'bugs', 'description', 'notification_emails'],
     'type': 'object'}

On instance['basic']['client_id']:
    {'bugs': [123456789],
     'description': 'A UUID identifying a profile and allowing '
                    'user-oriented correlation of data.\n',
     'lifetime': 'user',
     'notification_emails': ['telemetry-client-dev@mozilla.com'],
     'type': 'uuid'}
/Users/jalmeida/src/android-components/samples/glean/metrics.yaml: basic.client_id: __init__() got an unexpected keyword argument 'lifetime'

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at sdk_generator_346s0h22odhaxt6dncwxx2ezf$_run_closure3$_closure6$_closure7.doCall(/Users/jalmeida/src/android-components/components/service/glean/scripts/sdk_generator.gradle:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:739)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:712)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 34 more
</details>

**Comment by jonalmeida** [comment]
This seems to have disappeared with a clean build, but I seem to see it show up once in a while.

**Comment by Dexterp37** [comment]
Hi @jonalmeida and thanks for reporting this! I seem to be able to reproduce this problem. Basically, when some change in `android-components` that requires an updated version of `glean_parsers` is pulled locally, the Python environment in the build system will still use the cached version of the parsers, even though we're requiring  a new version.

While this problem can be worked around by triggering a clean build, as you found out, we definitely need a solid way to refresh the Python environment when needed.

@mdboom , thoughts? Is there any way we can make sure the library stays up to date?

**Comment by mdboom** [comment]
Thanks for the report, @jonalmeida.  This can probably solved by doing a force `pip` update.  I've self-assigned and am looking into this now.

**Comment by mdboom** [comment]
A fix is posted in https://github.com/mozilla-mobile/android-components/pull/1306

**Comment by jonalmeida** [comment]
Closing since this issue is merged.

**Comment by Dexterp37** [comment]
The issue wasn't merged yet, let's close this once the fix is merged and validated :)

**Comment by jonalmeida** [comment]
Nvm, might still need a review. I'm just going to leave it this up you. :)
