### ISSUE TITLE
Generated docs should present bug ids in human readable form

### ISSUE THREAD

**Issue by wlach** [mozilla/glean_parser#243]
Currently the glean parser generates documentation with bug reviews as "1". e.g.:

![image](https://user-images.githubusercontent.com/20569/95871714-f6d02600-0d3b-11eb-8caf-e9f6202db57d.png)
https://github.com/mozilla/mozregression/blob/master/docs/glean/metrics.md

It would be better if we gave a more human-readable form. In general data review URLs look like either this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1581647#c9

or this:

https://github.com/mozilla-mobile/fenix/pull/1707#issuecomment-486972209

For the former case, a better title would be "Bug 1581647". For the latter, we can use the GitHub convention of "mozilla-mobile/fenix#1707"

As part of this change, we should add some tests (this is probably the most involved part of this task) to https://github.com/mozilla/glean_parser/blob/main/tests/test_markdown.py

**Comment by wlach** [comment]
@alvesitalo would you like to give this a try? It's from a different repository from the glean dictionary, but is a related area. @mdboom has offered to mentor.

**Comment by mdboom** [comment]
@alvesitalo: You can just add questions to this issue, or find me in Element in the "#Glean Dictionary" channel.

**Comment by alvesitalo** [comment]
Hey, the markdown docs are now being generated like this in Data reviews column:

[Review 1](http://example.com/reviews) (A generic URL for review)
[Bug 1581647](https://bugzilla.mozilla.org/show_bug.cgi?id=1581647)
[mozilla-mobile/fenix#1707](mozilla-mobile/fenix#1707)

![bug-ids](https://user-images.githubusercontent.com/35741521/96182031-40bb3680-0f0b-11eb-9270-4c2921b17cf3.png)

I also added a test in test_markdown.py. Should I open a PR for code revision?

**Comment by mdboom** [comment]
Looks good. Yes, it would be great to see a PR, thanks.
