### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/glean_parser#34]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/glean_parser/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by Dexterp37** [comment]
@mdboom hey Mike, looks like I can't access repo settings. Would you mind making this change?

**Comment by mdboom** [comment]
@Dexterp37 : I gave you admin access, because it should have been more than just me all along.

However, it looks like the wiki has always been restricted to those with write access, and I don't see any public defacement in the history.  Perhaps this is a false positive error report?

**Comment by Dexterp37** [comment]
Thanks! I've removed Wiki support, just in case. We were not using it anyway.

**Comment by moz-hwine** [comment]
Not an intentional false positive -- the GitHub API doesn't provide access to that setting. :/

**Comment by mdboom** [comment]
Cool.  In any case, it's a great effort to reduce our defacable surface :)
