### ISSUE TITLE
kotlin.jinja2 missing import

### ISSUE THREAD

**Issue by boek** [mozilla/glean_parser#45]
* Glean Parser version: latest? (Not sure how to check
* Python version: 2.7.15rc1
* Operating System: Ubuntu 18.04

### Description

I added an event with no extra_keys, this properly created the `EventMetricType` with the generic requirement of `NoExtraKeys`. The problem is `import mozilla.components.service.glean.NoExtraKeys` needs to be in the file for it to compile

### What I Did

Compilation failed after I added the event here:

```
/home/boek/git/mozilla-mobile/fenix/app/build/telemetry/src/armGreenfieldDebug/kotlin/Events.kt: (85, 44): Unresolved reference: NoExtraKeys
```

If I manually added the import it worked.

**Comment by mdboom** [comment]
@boek: This should now be fixed on master in `android-components`.  Thanks for the report!
